// File generated by FlutterFire CLI.
// To regenerate this file, run: flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_v42c_J66nhExhyClDs58hxYEJYdqB0',
    appId: '1:917374329470:web:a45ede8ee2e04e067cee2f',
    messagingSenderId: '917374329470',
    projectId: 'vulnscan-finalyear',
    authDomain: 'vulnscan-finalyear.firebaseapp.com',
    storageBucket: 'vulnscan-finalyear.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2TRDXibDj8pvFV6iIJqkJrMUWev-ZRY',
    appId: '1:917374329470:android:70f76407ff121c287cee2f',
    messagingSenderId: '917374329470',
    projectId: 'vulnscan-finalyear',
    storageBucket: 'vulnscan-finalyear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW45I4xDykZCToEFmHdSkj3bHG9jtrcQA',
    appId: '1:917374329470:ios:159c3685b0d808e37cee2f',
    messagingSenderId: '917374329470',
    projectId: 'vulnscan-finalyear',
    storageBucket: 'vulnscan-finalyear.firebasestorage.app',
    iosBundleId: 'com.example.vulnscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW45I4xDykZCToEFmHdSkj3bHG9jtrcQA',
    appId: '1:917374329470:ios:159c3685b0d808e37cee2f',
    messagingSenderId: '917374329470',
    projectId: 'vulnscan-finalyear',
    storageBucket: 'vulnscan-finalyear.firebasestorage.app',
    iosBundleId: 'com.example.vulnscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0_v42c_J66nhExhyClDs58hxYEJYdqB0',
    appId: '1:917374329470:web:fc50acd8e5f65a127cee2f',
    messagingSenderId: '917374329470',
    projectId: 'vulnscan-finalyear',
    authDomain: 'vulnscan-finalyear.firebaseapp.com',
    storageBucket: 'vulnscan-finalyear.firebasestorage.app',
  );

}